### ISSUE TITLE
SecretSwap's Balances

### ISSUE THREAD

**Issue by sacredwx** [enigmampc/SecretSwap#3]
Hello guys,
I see that SecretSwap's balances are publicly accessible, hence the viewing key is static and public,
here I see a possible attack vector, where everyone can monitor the network and see the balance changes after each tx.
Not private enough I think..
Am I right?

**Comment by assafmo** [comment]
You are correct. Pools' balances must be public to allow for price discovery. Token swaps are not private, but they are resistant to front running attacks, and before and after a swap you can privately transfer the tokens to a new wallet.

**Comment by sacredwx** [comment]
> You are correct. Pools' balances must be public to allow for price discovery. Token swaps are not private, but they are resistant to front running attacks, and before and after a swap you can privately transfer the tokens to a new wallet.

Got ya! thanks!
